#!/bin/bash

read -p "Email: " EMAIL

# Git SSH connection and configs
git config --global user.email $EMAIL

ssh-keygen -t rsa -b 4096 -C $EMAIL
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
sudo pacman -S xclip; sudo apt install xclip -y
xclip -sel clip < ~/.ssh/id_rsa.pub 
echo "Copy public key to Github"
echo "The public key is:"
cat ~/.ssh/id_rsa.pub
read -n 1 -s -r -p "When you are done with Github, press any key to continue "
echo
ssh -T git@github.com
echo "${GREEN}SSH connection with Github is done"

#Insert email for git
git config --global user.email $EMAIL
