#!/bin/bash

GREEN=`tput setaf 2`

chmod u+x aliases configure_git installs

# Git directory stuff
mkdir -p ~/Documents/code/git
ln -s ~/Documents/code/git ~/git
echo "${GREEN} Git directory is created"

./configure_git
echo "${GREEN} Git directory is created"

./aliases
echo "${GREEN} Aliases are set"

./installs 
echo "${GREEN} Packages are installed"

# Make sure date and time are correct (for Manjaro)
# sudo pacman -S ntp
# sudo timedatectl set-ntp true
# echo "${GREEN} Time is set correctly"

# Remove execute permission from every file
chmod -x *